version: '3'

services:

    web:
        build: .
        container_name: web_midterm
        ports:
            - 5028:5000
        volumes:
            - ./list/animals.json:/data_file.json

    redis:
        image: redis:latest
        ports:
            - 6408:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]
