---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as88662-test-pvc-deployment
  labels:
    username: as88662
    env: test
    app: as88662-test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as88662-test-redis
  template:
    metadata:
      labels:
        username: as88662
        env: test
        app: as88662-test-redis
    spec:
      containers:
        - name: as88662-test-redis
          imagePullPolicy: Always
          image: redis:5.0.0
          volumeMounts:
          - name: as88662-test-pvc-data
            mountPath: "/data"
      volumes:
      - name: as88662-test-pvc-data
        persistentVolumeClaim:
          claimName: as88662-test-pvc-data
