---
apiVersion: v1
kind: Service
metadata:
  name: as88662_test
  labels:
    username: as88662
    env: test
spec:
  type: ClusterIP
  selector:
    app: helloflask
  ports:
  - name: helloflask
    port: 6408
    targetPort: 6408
