---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as88662-test-flask-deployment
  labels:
    app: as88662-test-flask
    username: as88662
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: as88662-test-flask
  template:
    metadata:
      labels:
        app: as88662-test-flask
        username: as88662
        env: test
    spec:
      containers:
        - name: as88662-test-animals
          imagePullPolicy: Always
          image: Aanchalaanchal/Aanchalaanchal_web
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
