---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as88662_test
  labels:
    username: as88662
    env: test
    app: as88662-test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hellos
          image: redis:5.0.0
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
          volumeMounts:
          - name: as88662_test
            mountPath: "/data"
