---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: as88662_test
  labels:
    username: as88662
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
