---
apiVersion: v1
kind: Service
metadata:
  name: as88662-test-redis-service
  labels:
    username: as88662
    env: test
spec:
  type: ClusterIP
  selector:
    app: as88662-test-redis
  ports:
  - name: as88662-test-redis-service
    port: 6379
    targetPort: 6379
