---
apiVersion: v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      greeting: Personalized
  replicas: 3
  template:
    metadata:
      labels:
        greeting: Personalized
    spec:
      containers:
        - name: hello
          image: ubuntu:18.04
          command: ['sh', '-c', 'echo Hello, $NAME && sleep 3600']
          imagePullPolicy: IfNotPresent
          env:
            - name: NAME
              value: "Aanchal"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
